# file cấu hình cho tài khoản database
# db.ulr: Là đường dẫn tới Database quanlythuvien để lấy dữ liệu
# db.user: Là tên username của Database của bạn
# db.password: Là mật khẩu của Database của bạn
db.url=jdbc:mysql://localhost:3306/quanlythuvien?useUnicode=true&characterEncoding=UTF-8
db.user=root
db.password=MatKhauBiMatCuaToi
